### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by wjholden** [blechschmidt/freebind#6]
I am doing research in a related field of IPv6 source address randomization. I would like to cite Freebind as prior work. Is there anything you would like added to this Bibtex citation? 

```
@software{freebind,
  author = {Blechschmidt, B},
  title = {{Freebind}},
  url = {https://github.com/blechschmidt/freebind},
  year = {2023}
}
```

**Comment by blechschmidt** [comment]
Hi,

it would be great if you could cite my full name:
```
@software{freebind,
  author = {Blechschmidt, Birk},
  title = {{Freebind}},
  url = {https://github.com/blechschmidt/freebind},
  year = {2023}
}
```

Thanks a lot.
